### ISSUE TITLE
heading--null  class applied when display not set

### ISSUE THREAD

**Issue by Azersi** [AlaskaAirlines/auro-header#2]
## Describe the bug
When the display attribute is not defined, the header element is given a class of heading--null, rather than a default value.

## To Reproduce
1. Create <auro-header> component and set the level to any value
2. The H1..6 element will have a class on it called heading-null

## Expected behavior
null should not be apart of the class name, or a default should be set.

## Screenshots
![image](https://user-images.githubusercontent.com/16887514/87487858-a2f65980-c5f3-11ea-9601-95f8df0f9d73.png)

**Comment by blackfalcon** [comment]
What is the HTML that created this output? A [default](https://github.com/AlaskaAirlines/auro-header/blob/master/src/auro-header.js#L18) is set. See attached screenshot. Unable to repro. 
<img width="503" alt="Screen Shot 2020-07-14 at 11 01 33 PM" src="https://user-images.githubusercontent.com/181089/87509248-04372080-c626-11ea-8e8e-ab67ad1efd4b.png">

I could put a catch in there that if `display=""` then I can force the default back in. But I am not sure that this is the problem.

**Comment by blackfalcon** [comment]
In reviewing this further, the issue seems to be a use case where the `display` prop is removed from the DOM. The WC is not re-rendering on this update and then updates the prop value with `null`.
