### ISSUE TITLE
auro-header: blueprint

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-header#28]
# Blueprint
We need a blueprint for auro-header that matches the features we have currently on our doc site.

## Outline tasks

- [ ] anatomy
- [ ] color
- [ ] typography
- [ ] layout
- [ ] spacing
- [ ] animation/behavior
- [ ] variants
- [ ] states (hover, focus, active, focus-visible)
- [ ] a11y

## Optional

- [ ] Competitive analysis
- [ ] research
- [ ] site audit
- [ ] usage audit
- [ ] inspirational work

**Comment by Patrick-Daly-AA** [comment]
blueprint for header is not needed.  It would literally just be text.  closing.
