### ISSUE TITLE
type="px" conflicts with margin

### ISSUE THREAD

**Issue by ychae-alaska** [AlaskaAirlines/auro-header#3]
## Describe the bug
When using `type="px"` for auro headers, the `margin` attribute is overridden by `:host([type="px") .header-400`. 

## To Reproduce
1. Define `type="px"` on header attribute
2. Specify `margin="top"` (or "bottom") with any size
3. Inspect element styles and you can see the margin style is overridden.

## Expected behavior
Margin attribute should appear with pixels as opposed to rem or being overridden. 

## Screenshots

Using `type="px"`:
![image](https://user-images.githubusercontent.com/69012103/88959914-96127080-d257-11ea-8181-d217f7abc562.png)

`type="px"` overriding `margin`:
![image](https://user-images.githubusercontent.com/69012103/88959940-9dd21500-d257-11ea-8ba6-00871e39887a.png)

Not using `type="px"`:
![image](https://user-images.githubusercontent.com/69012103/88959958-a4f92300-d257-11ea-879a-37b625a643c7.png)

`Margin `is configured correctly:
![image](https://user-images.githubusercontent.com/69012103/88959973-aaef0400-d257-11ea-8bc0-a7c54494243d.png)

## Desktop (please complete the following information):
 - Browser [Chrome, Edge, Firefox] **Did not check IE or Safari
 - Version [windows 10]

## Smartphone (please complete the following information):
N/A

**Comment by blackfalcon** [comment]
Reviewed issue. In progress for resolution.
