### ISSUE TITLE
auro-header: Insufficient line height when display="200" 

### ISSUE THREAD

**Issue by jordanchang** [AlaskaAirlines/auro-header#35]
## Describe the bug
The line-height is insufficient when Auro-header with display="200" is used.

## To Reproduce
1. Add a <auro-header display="200">
2. Enter a long header text such as Signature Fruit and Cheese Platter
3. Header is rendered and the text should wrap
4. Line-height 1.5rem from essentials.css causes the next line to be rendered too close.

## Expected behavior
Line-height should be increased to allow adequate spacing when text is wrapped.

## Screenshots
auro-header display=200
![image](https://user-images.githubusercontent.com/3304352/169879313-50fa0daf-4b8e-4183-910f-2d300f4db5ba.png)

Disabling line-height from essentials.css yields a better UI
![image](https://user-images.githubusercontent.com/3304352/169879787-b10397e6-aa6f-416b-a2f4-5655400e809c.png)

## Desktop (please complete the following information):
 - OS: MacOS
 - Browser: Chrome
 - Version: latest

## Smartphone (please complete the following information):
untested

## Additional context
None

**Comment by blackfalcon** [comment]
@leeejune you interested in addressing this? The fix would be to enforce a different line-height rule in the scope fo the element that will override essentials.

**Comment by leeejune** [comment]
@blackfalcon I'm not sure if I understand "in the scope of the element that will override essentials". 

Can that header be a text token instead?

**Comment by blackfalcon** [comment]
@jordanchang I dug into this a little and the core issue here is that we do not support a `200` style. Please see the API we support. https://auro.alaskaair.com/components/auro/header/api#:~:text=Use%20fixed%20feature.-,Properties,-Property
