### ISSUE TITLE
As a developer I want to be able to change the header display size for when the screen size reaches a breakpoint.

### ISSUE THREAD

**Issue by danhiel** [AlaskaAirlines/auro-header#39]
# General Support Request

## Support request
I want to set the header to a different size from the original size when the screen size changes. More specifically, when the screen size changes from desktop to a mobile screen, I want to be able to resize the header display.

## Possible Solution
A solution would be using or enabling a CSS media query. We have tried the fixed attribute but that didn't work.

## Context
For desktop, the header display is 600. For mobile, I want the header display to shrink to 400.

## Your Environment
Browser: Chrome (Latest)
OS: Windows 10 Desktop
https://github.com/Alaska-ECommerce/PreorderFoodWeb

**Comment by blackfalcon** [comment]
@danhiel sorry... just now seeing this one. The header CSS [already is using media queries](https://github.com/AlaskaAirlines/auro-header/blob/master/src/style.scss) for specific scenarios. This is not specifically a feature we can add to the header component but is more so a change with the base design of the headers themselves. 

I'd suggest reaching out to @leeejune to discuss what the current spec is and the additional options you are looking for.
