### ISSUE TITLE
auro-header: independent top/bottom margins

### ISSUE THREAD

**Issue by ftaylor-alaska** [AlaskaAirlines/auro-header#4]
## Is your feature request related to a problem? Please describe.
Consumers of the auro-header are limited to adjust either the top or bottom margin, but not both.

## Describe the solution you'd like
As a developer for AScom, I would like to see the auro-header have the ability to specify both the top and bottom margin adjustments.  (Having full independent control of both top and bottom would be a nice-to-have, but the below alternative should be fine).

## Describe alternatives you've considered
A simpler solution would be to have the option to set top/bottom margin to be both be the same 'size' value.

## Additional context
Currently these are the two attributes which allow the consumer of this component to adjust the top or bottom:
![image](https://user-images.githubusercontent.com/51933786/92658230-11c9f900-f2ab-11ea-88fb-8c0a375cfae7.png)

**Comment by blackfalcon** [comment]
Help to better understand the use case. Is the option that the top/bottom adjustments would be identical or independent. E.g. Top xs, Bottom lg, or Top/Bottom lg.

**Comment by ftaylor-alaska** [comment]
I think that we would like to have the prior example (top - xs, bottom - lg)
