### ISSUE TITLE
Update custom component name registration capability 

### ISSUE THREAD

**Issue by Izook** [AlaskaAirlines/auro-header#58]
## Is your feature request related to a problem? Please describe.

I want to be able to register the `auro-header` to a custom name (e.g. `hf-auro-header`) so that I can introduce a specific version of the `auro-header` to pages without breaking other experiences on the page that may be dependent on a different version of `auro-header`. 

## Describe the solution you'd like

Repeat the solution implemented here [auro-header#152](https://github.com/AlaskaAirlines/auro-hyperlink/pull/152) and here [auro-hyperlink#154](https://github.com/AlaskaAirlines/auro-hyperlink/pull/154) which will expose a function `registerComponent` which will allow consumers to choose what element name the component is registered to. 

## Describe alternatives you've considered

Forcing all experiences on the page to use the same component version. Not ideal because that could break experiences when one needs to update. 

## Additional context

A good article explaining the issue can be found here: https://dev.to/florianrappl/versioning-web-components-3bda

Related Issue [auro-icon#60](https://github.com/AlaskaAirlines/auro-icon/issues/60)

**Comment by blackfalcon** [comment]
Added this issue and it requries issue refinement similar to other Node 18+ updates.
