### ISSUE TITLE
Release is missing required assets 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-header#86]
### Please verify the version of auro-badge you have installed

1.5.3

### Please describe the bug

The delivered version of `index.js` has a dependency on `./src/auro-header.js` which is not in the delivered package. We need to update the package and include `./src/auro-header.js`

### Expected behavior

The installed element should operate as expected. 

> This issue was copied from [#56](https:&#x2F;&#x2F;github.com&#x2F;AlaskaAirlines&#x2F;auro-badge&#x2F;issues&#x2F;56) by @blackfalcon.

**Comment by blackfalcon** [comment]
The issue is related to the fact that the src resources are not included with the npm package. 

See this file as a reference to correct. 
https://github.com/AlaskaAirlines/auro-hyperlink/blob/main/.npmignore

## Exit criteria 

This issue can be closed once the update includes the necessary components of the source files.

**Comment by fajar-apri-alaska** [comment]
Actually, this was done in [1.5.4 commit](https://github.com/AlaskaAirlines/auro-header/commit/233365fb4f9c4eb0c77edf997adbd52f64ee34c1).

Should I remove mine then? @blackfalcon

**Comment by blackfalcon** [comment]
The 1.5.4 commit was done to address an immediate need. This whole update will negate that commit. Please REBASE this branch off of the current MASTER release and then make sure that the code is in [this](https://github.com/AlaskaAirlines/auro-header/pull/84/files#diff-34958b02363eec9a904716f0b4a8782b021c6b33b2e8599019e36c88e045240b) state.

**Comment by Izook** [comment]
@fajar-apri-alaska @blackfalcon lets keep this one open, looks like we accidentally blocked a little more than we intended: 

![image](https://user-images.githubusercontent.com/23248722/232910477-c20096fe-407a-495b-b31c-4cfedd4a34b2.png)

![image](https://user-images.githubusercontent.com/23248722/232910516-f999c271-4707-43fb-8d84-01443d26aee0.png)

Gonna submit a PR with a fix to this soon

**Comment by blackfalcon** [comment]
@Izook yeah, I picked up on that just a few minutes ago. I can address this fast.
