### ISSUE TITLE
<auro-header> doesn't shrink to allow the display of a 26-character first name (or even 16-character text) on one line

### ISSUE THREAD

**Issue by Sara-Jade** [AlaskaAirlines/auro-header#94]
### Please verify the version of auro-header you have installed

"@aurodesignsystem/auro-header": "^2.0.0"

### Please describe the bug

Bug affects all environments, browsers. Repro steps are for prod in a Chrome incognito window.

1. Use VPN, an on-prem connection, or a non-Alaska-issued device.
2. Turn off any SwitchHost proxying.
3. Open an incognito window in Chrome.
4. Go to as.com and sign-in with a prod test account that has not made a 100K Benefit Choice.
![SwtichHosts has no proxy. About to login to as.com.](https://github.com/AlaskaAirlines/auro-header/assets/88349392/3bbcd1ab-3156-442e-a634-19d33a3c8979)
5. Navigate to https://www.alaskaair.com/account/mpchoice
![account signed in to mpchoice](https://github.com/AlaskaAirlines/auro-header/assets/88349392/ed3421b4-984c-442f-a1c3-ef662b8eb847)
7. Observe the "Congratulations..." header, which uses the `<auro-header>` component.
6. Shrink the width of the page to 320px with dev tools.
![broken header](https://github.com/AlaskaAirlines/auro-header/assets/88349392/7b2ab5ed-6933-4f81-9708-32defa6642c9)
8. Observe that the word "Congratulations," breaks across lines.

Notes: 
- Mileage Plan account first names may be up to 26 characters long. `<auro-header>` can't even accommodate the 16 characters in "Congratulations," on one line.
- The issue is reproducible on the Auro doc site:
![auro-header overflow](https://github.com/AlaskaAirlines/auro-header/assets/88349392/64dfab9d-9074-44a7-bdda-4604e11435b8)

### Reproducing the error on the docsite

This issue is reproducible on the Auro docsite

### Expected behavior

The `<auro-header>` should shrink to fit the width of the screen to a screen width of 320px and a first name of 26 characters.

### What browsers are you seeing the problem on?

Chrome

### Exit criteria

Stakeholder:
As a Mileage Plan member using my tiny phone
Scenario
I want to login to my benefits site, and see my 26-character first name on one line.

**Comment by Patrick-Daly-AA** [comment]
Introducing dynamically changing font sizes as a built in default functionality of the component is outside of the scope of capabilities we want to include.
